[tool.poetry]
name = "calculator"
version = "0.1.0"
description = ""
authors = ["kevcifu <kevins_cifuentes@soy.sena.edu.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
